### PR TITLE
Fix leak of ibrowse connections

### PR DESCRIPTION
**Pull request by stevendanna**
When a connection hits max_connection_request or max_connection_duration,
we kill the old ibrowse process and make a new ibrowse process.
However, we were also making a new ibrowse client when we received the
EXIT from the previous ibrowse process we killed. Thus, leaving us with
2 ibrowse processes. This pattern would continue, continually leaking
processes. Each of these ibrowse processes maintains an open TCP
connection.

In the context of chef-server, on high traffic servers this could cause
the authorization service to quickly reach its maximum-allowed
concurrent connections.

This commit only calls make_http_client_pid when we receive a normal
exit from our current ibrowse_pid. We handle exit messages from other
processes by ignoring them.

It also removes the tracking of kill_expected which appears unnecessary
given the above change.

### CODE REVIEW

**Comment by stevendanna** [comment]
Happy to entertain other fixes if I've missed something.  But the leak definitely exists currently on master and this fixes it for the cases I've been testing locally.  cc @chef/lob @oferrigni

**Comment by oferrigni** [comment]
Looks reasonable to me. Would be great if we could write tests that examine this behavior/change.

**Comment by stevendanna** [comment]
@oferrigni Added a test for whether we are leaking ibrowse processes.  It is a bit ugly.

**Comment by danielsdeleo** [comment]
I'm a bit out of my depth here, but is there any possibility we could now fail to make a new ibrowse process in response to a legitimate failure?

**Comment by stevendanna** [comment]
@danielsdeleo I think what will happen now is that if our ibrowse process crashes (i.e. exits with a reason other than normal), our entire worker will crash.  Pooler should handle that and start another one.

**Comment by danielsdeleo** [comment]
Makes sense. :+1: from me, though review from someone with more OTP skills would probably be good.

**Pull request merged**
